# Generated by Django 4.2.3 on 2023-07-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfEvent', models.CharField(max_length=64)),
                ('idOfEvent', models.CharField(max_length=64)),
                ('dataOfEvent', models.CharField(max_length=64)),
                ('latOfEvent', models.FloatField()),
                ('lonOfEvent', models.FloatField()),
                ('desc', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
