# Generated by Django 4.2.3 on 2023-07-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_events', '0004_weatherevent_alter_event_countryofevent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeatherEvent',
        ),
        migrations.AlterField(
            model_name='event',
            name='countryOfEvent',
            field=models.CharField(default='peaky', max_length=64),
        ),
    ]
