# Generated by Django 4.2.3 on 2023-07-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_events', '0007_rename_create_at_event_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=64)),
                ('flights_going', models.JSONField()),
                ('flights_backhome', models.JSONField()),
            ],
        ),
    ]
